# Use docker-based build environment (instead of openvz)
sudo: false
language: scala
jdk:
- oraclejdk8

matrix:
  include:
    - scala: 2.11.12
      env: PLAY_VERSION=2.5
    - scala: 2.11.12
      env: PLAY_VERSION=2.6
    - scala: 2.12.8
      env: PLAY_VERSION=2.6

cache:
  directories:
    - '$HOME/.ivy2/cache'
    - '$HOME/.sbt'

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/4f1883358fd00b380a4e'
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
